# https://docs.helix-editor.com/configuration.html

# https://github.com/helix-editor/helix/wiki/Themes
theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
true-color = true
bufferline = "multiple"
# text-width = 120

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control"]
right = [
  "file-name",
  "file-modification-indicator",
  "diagnostics",
  "separator",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "position",
]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
space = "none"
nbsp = "all"
newline = "all"

[editor.whitespace.characters]
newline = "↲"

[editor.indent-guides]
render = true

# [editor.soft-wrap]
# enable = true
# wrap-at-text-width = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

# https://github.com/helix-editor/helix/discussions/6468
[keys.normal.space]
Z = ":set gutters.line-numbers.min-width 3"
z = ":set gutters.line-numbers.min-width 117" # Width is 350
